name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          IMAGE_NAME=rv64
          cd docker
          docker build . --file Dockerfile --tag $IMAGE_NAME
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/images:$IMAGE_NAME
          docker push ${{ secrets.DOCKER_USERNAME }}/images:$IMAGE_NAME
